Fixing a couple of issues here...
src/LoginModules.ts:14:20 - error TS2503: Cannot find namespace 'puppeteer'.
src/TokenCache.ts:60:20 - error TS2503: Cannot find namespace 'puppeteer'.
and...
src/TokenCache.ts:99:24 - error TS2339: Property 'waitFor' does not exist on type 'Page'.

These are fixed by simple oneliner changes.